import {writeFileSync} from 'node:fs';
import {chapters} from './chapters.mjs';
const pad=n=>String(n).padStart(2,'0');
const toc=chapters.map((c,i)=>`<a href="#${c.id}"><span>${pad(i+1)}</span>${c.short}</a>`).join('');
const sections=chapters.map((c,i)=>`<section class="chapter" id="${c.id}" aria-labelledby="title-${c.id}"><header class="chapter-head"><p class="eyebrow">第 ${pad(i+1)} 章 · ${c.theme}</p><h2 id="title-${c.id}">${c.title}</h2><p class="chapter-deck">${c.deck}</p></header><div class="prose">${c.body}</div>${i<chapters.length-1?`<a class="next-chapter" href="#${chapters[i+1].id}"><span>带着这个问题，继续往下读</span><strong>${chapters[i+1].short} <b aria-hidden="true">↗</b></strong></a>`:''}</section>`).join('');
writeFileSync('dist/index.html',`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="从一次鸟类观测出发，读懂物种分布模型的原理、检验和应用。一堂有例子、有真实结果的中文生态学课。"><meta name="robots" content="index,follow"><meta name="theme-color" content="#f5f5f7"><title>一只鸟，一张地图｜物种分布模型，慢慢讲明白</title><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='16' fill='%231d3937'/%3E%3Cpath d='M14 39Q24 16 32 33Q41 16 52 26Q40 26 33 47Q24 29 14 39' fill='white'/%3E%3C/svg%3E"><link rel="stylesheet" href="style.css"><script src="app.js" defer></script></head>
<body><a class="skip-link" href="#story">跳到正文</a><header class="site-header"><a class="wordmark" href="#top">一只鸟，一张地图<span>生态学的中文课堂</span></a><nav aria-label="主导航"><a href="#story">开始阅读</a><a href="#contents">章节目录</a><a href="#sources">资料出处</a></nav></header>
<main id="top"><section class="hero"><div class="hero-copy"><p class="eyebrow">物种分布模型 · 从原理到实践</p><h1>一只鸟，<br>一张地图。<span>中间的故事，慢慢讲。</span></h1><p>我们在一片湿地看见了鸟。<br>怎样从这条记录，走到“下一次应该去哪里找”？</p><a class="primary-link" href="#story">从这次观测开始 <span aria-hidden="true">↗</span></a></div><figure class="hero-image"><img src="assets/ai-01-crane-observation.jpg" width="1672" height="941" alt="晨雾中的湿地，一只丹顶鹤站在浅水边" fetchpriority="high"><figcaption>湿地里的一个清晨 · AI 场景配图</figcaption></figure></section>
<section class="intro" id="contents"><p class="eyebrow">这堂课怎样展开</p><h2>先想清楚问题，<br>再看懂方法为何出现。</h2><p>你不需要先记住一串算法名称。我们从一条观测记录讲起：记录有什么含义，地图上的空白怎样理解，模型怎样学出规律，又该怎样判断这张地图值不值得用。每一步，都从前一步留下的问题出发。</p><div class="reading-route"><span>读懂记录</span><span>建立关系</span><span>检验地图</span><span>走向现场</span></div><details class="mobile-contents"><summary>展开十二章目录</summary><nav>${toc}</nav></details></section>
<div class="reading-layout" id="story"><aside class="sidebar"><div class="sticky-toc"><p>沿着问题往下走</p><nav aria-label="章节目录">${toc}</nav><a class="source-nav" href="#sources">课程与文献出处 ↗</a></div></aside><div class="chapters">${sections}</div></div>
<section class="sources" id="sources"><div><p class="eyebrow">继续追问时，从这里出发</p><h2>每一步，都有来处。</h2><p>这是 David Chen 基于公开课程资料整理的独立中文学习讲解网站。它不是课程官方页面，也不代表课程作者或其所属机构的立场。</p><h3>页面中的内容怎样区分</h3><ul><li><strong>课程结果：</strong>来自固定代码版本与配套数据的本地适配运行，分析图由这些结果重新绘制。</li><li><strong>本站解释：</strong>中文叙述、教学算例和延伸研究设计由本站独立整理。</li><li><strong>教学例子：</strong>为说明计算而设置，文中会明确标出。</li><li><strong>图片与论文：</strong>AI 场景图只帮助理解情境，不是野外照片或分析证据；论文观点均附原文入口。</li></ul></div><div class="source-body"><h3>课程代码与数据</h3><p><a href="https://github.com/qiaohj/ENM_curriculum/tree/4936e2e940968766340ed2788f983ae210930258" target="_blank" rel="noopener">乔慧捷老师的课程代码 · 固定版本 ↗</a><br><a href="https://doi.org/10.6084/m9.figshare.33453802.v2" target="_blank" rel="noopener">课程配套数据 · 第 2 版 ↗</a></p><p>课程代码：Copyright © 2026 Qiao, Huijie，采用 <a href="https://github.com/qiaohj/ENM_curriculum/blob/4936e2e940968766340ed2788f983ae210930258/LICENSE" target="_blank" rel="noopener">MIT License</a>。课程配套数据引用为 Qiao, Huijie (2026), <em>SDM curriculum</em>, Figshare, version 2，采用 <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>。完整许可通知见 <a href="THIRD_PARTY_NOTICES.txt">第三方材料与许可说明</a>。</p><p>本站进行了运行适配、指标汇总、图形重绘、中文解释和标签整理；下载表是运行结果的汇总副本，不包含原始气候栅格或专家范围图层。课程中的丹顶鹤、灰松鼠和煤山雀分别承接不同问题，这里用一条连续的讲解线把练习连接起来。</p><details><summary>查看复现结果、章节对应与原始数值</summary><p>每章末尾列出对应课程练习及论文页码。表格保留原始英文列名，便于与代码逐项核对；其中 D5、D15 的验证与背景标签依据实际代码校正，原始数值保留。</p><ul><li><a href="assets/occurrence-flow.csv">记录整理过程</a></li><li><a href="assets/model-metrics.csv">模型评价结果</a></li><li><a href="assets/model-settings.csv">模型设置</a></li><li><a href="assets/D14-model-evaluations.csv">煤山雀数量预测结果</a></li><li><a href="assets/D4-sensitivity-range-change.csv">环境变化教学情景</a></li></ul></details><p class="fine-print">本站中文讲解与页面设计 © 2026 David Chen。引用课程代码、数据或论文时，请同时回到相应原始来源。占域、联合物种模型与声学应用属于本站延伸讲解。</p></div></section></main>
<footer><a href="#top">一只鸟，一张地图</a><span>独立学习讲解网站 · 非课程官方页面</span><a href="#top">回到开头 ↑</a></footer><dialog id="figure-dialog" aria-label="放大查看分析图"><button class="close-dialog" aria-label="关闭大图">关闭 ×</button><img alt=""><p></p></dialog></body></html>`);
console.log(`Built ${chapters.length} chapters.`);
